import type { Place } from '../types'

export const mockPlaces: Place[] = [
  {
    id: '1',
    created_at: '2024-02-14T00:00:00Z',
    name: 'La Trattoria',
    type: 'restaurante',
    city: 'Bogotá',
    country: 'Colombia',
    visit_date: '2024-02-14',
    rating_him: 4.7,
    rating_her: 4.9,
    rating_avg: 4.8,
    price_level: 2,
    would_return: true,
    story: 'Primera cita. Llegamos sin reserva y nos dieron la mejor mesa. La pasta era perfecta y el vino nos hizo hablar hasta las 11 de la noche.',
    comment_him: 'El lugar donde todo empezó. Imposible olvidarlo.',
    comment_her: 'Volvería mil veces. La pasta carbonara más rica que he probado.',
    lat: 4.6533,
    lng: -74.0558,
    photos: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
      'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80',
    ],
    is_favorite: true,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['primera cita', 'italiano', 'romántico'],
  },
  {
    id: '2',
    created_at: '2025-04-12T00:00:00Z',
    name: 'Cartagena',
    type: 'ciudad',
    city: 'Cartagena',
    country: 'Colombia',
    visit_date: '2025-04-12',
    rating_him: 4.8,
    rating_her: 5.0,
    rating_avg: 4.9,
    price_level: 3,
    would_return: true,
    story: 'Nuestro primer viaje largo juntos. Nos perdimos por el centro histórico, comimos en el mercado, vimos el atardecer desde las murallas. Perfecto.',
    comment_him: 'El mejor viaje que hemos hecho. El calor era intenso pero los recuerdos son increíbles.',
    comment_her: 'Quiero volver. Las murallas al atardecer son de otro mundo.',
    lat: 10.3910,
    lng: -75.4794,
    photos: [
      'https://images.unsplash.com/photo-1583682064285-79b3d7bcf5b5?w=800&q=80',
      'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=800&q=80',
    ],
    is_favorite: true,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['playa', 'historia', 'caribe'],
  },
  {
    id: '3',
    created_at: '2025-08-16T00:00:00Z',
    name: 'Villa de Leyva',
    type: 'pueblo',
    city: 'Villa de Leyva',
    country: 'Colombia',
    visit_date: '2025-08-16',
    rating_him: 4.7,
    rating_her: 4.9,
    rating_avg: 4.8,
    price_level: 2,
    would_return: true,
    story: 'Fuimos sin planearlo mucho y terminamos caminando por todo el pueblo, las calles empedradas y la comida fueron perfectas. Un día simple que se sintió increíble.',
    comment_him: 'Me encanta caminar contigo por las calles. Es un lugar mágico.',
    comment_her: 'La comida estuvo increíble y quiero volver.',
    lat: 5.6333,
    lng: -73.5250,
    photos: [
      'https://images.unsplash.com/photo-1598887142487-3c854d51eabb?w=800&q=80',
      'https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=800&q=80',
    ],
    is_favorite: true,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['colonial', 'arquitectura', 'tranquilo'],
  },
  {
    id: '4',
    created_at: '2024-07-20T00:00:00Z',
    name: 'El Cocuy',
    type: 'pueblo',
    city: 'El Cocuy',
    country: 'Colombia',
    visit_date: '2024-07-20',
    rating_him: 4.5,
    rating_her: 4.8,
    rating_avg: 4.7,
    price_level: 1,
    would_return: true,
    story: 'La montaña más alta que hemos subido juntos. El frío era brutal pero la vista desde arriba valió cada paso.',
    comment_him: 'Una aventura que nunca olvidaré.',
    comment_her: 'El paisaje me dejó sin palabras.',
    lat: 6.4024,
    lng: -72.4527,
    photos: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['montaña', 'aventura', 'naturaleza'],
  },
  {
    id: '5',
    created_at: '2024-11-15T00:00:00Z',
    name: 'Mompox',
    type: 'pueblo',
    city: 'Mompox',
    country: 'Colombia',
    visit_date: '2024-11-15',
    rating_him: 4.6,
    rating_her: 4.6,
    rating_avg: 4.6,
    price_level: 1,
    would_return: true,
    story: 'Un pueblo detenido en el tiempo. El río, los pelícanos y las calles vacías al amanecer fueron algo especial.',
    comment_him: 'Llegamos y sentimos que retrocedimos en el tiempo.',
    comment_her: 'El silencio del río en la mañana es algo que no olvidaré.',
    lat: 9.2426,
    lng: -74.4254,
    photos: [
      'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['patrimonio', 'río', 'colonial'],
  },
  {
    id: '6',
    created_at: '2025-03-08T00:00:00Z',
    name: 'Hotel W Bogotá',
    type: 'hotel',
    city: 'Bogotá',
    country: 'Colombia',
    visit_date: '2025-03-08',
    rating_him: 4.4,
    rating_her: 4.6,
    rating_avg: 4.5,
    price_level: 4,
    would_return: true,
    story: 'Una noche especial en la ciudad. La vista desde el piso 20 y el desayuno en la terraza lo convirtieron en algo memorable.',
    comment_him: 'El bar del lobby tiene los mejores cócteles.',
    comment_her: 'El servicio fue impecable, me sentí como una reina.',
    lat: 4.6709,
    lng: -74.0524,
    photos: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['lujo', 'ciudad', 'vista'],
  },
  {
    id: '7',
    created_at: '2025-06-22T00:00:00Z',
    name: 'Mongüí',
    type: 'pueblo',
    city: 'Mongüí',
    country: 'Colombia',
    visit_date: '2025-06-22',
    rating_him: 4.5,
    rating_her: 4.7,
    rating_avg: 4.6,
    price_level: 1,
    would_return: false,
    story: 'El pueblo de los balones. Paseamos por la plaza, tomamos chocolate caliente y nos tomamos mil fotos en las calles empedradas.',
    comment_him: 'El frío y la neblina le dan un ambiente único.',
    comment_her: 'Muy lindo pero muy frío para mí.',
    lat: 5.7281,
    lng: -72.8913,
    photos: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['boyacá', 'frío', 'colonial'],
  },
  {
    id: '8',
    created_at: '2024-05-10T00:00:00Z',
    name: 'Sushi Nikkei',
    type: 'restaurante',
    city: 'Bogotá',
    country: 'Colombia',
    visit_date: '2024-05-10',
    rating_him: 4.2,
    rating_her: 3.8,
    rating_avg: 4.0,
    price_level: 3,
    would_return: false,
    story: 'Probamos el sushi nikkei en Bogotá. El servicio tardó mucho pero la comida valió la espera.',
    comment_him: 'La espera fue larga pero la comida estuvo bien.',
    comment_her: 'No repetiría, aunque el tiradito estaba bueno.',
    lat: 4.6751,
    lng: -74.0485,
    photos: [
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: false,
    priority: null,
    budget: null,
    planned_year: null,
    tags: ['japonés', 'nikkei'],
  },
  // Planned places
  {
    id: '9',
    created_at: '2026-01-01T00:00:00Z',
    name: 'Japón',
    type: 'ciudad',
    city: 'Tokio',
    country: 'Japón',
    visit_date: '',
    rating_him: 0,
    rating_her: 0,
    rating_avg: 0,
    price_level: 4,
    would_return: null,
    story: null,
    comment_him: null,
    comment_her: null,
    lat: 35.6762,
    lng: 139.6503,
    photos: [
      'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: true,
    priority: 'alta',
    budget: '$$$',
    planned_year: 2027,
    tags: ['asia', 'cultura', 'gastronomía'],
  },
  {
    id: '10',
    created_at: '2026-01-01T00:00:00Z',
    name: 'Italia',
    type: 'ciudad',
    city: 'Roma',
    country: 'Italia',
    visit_date: '',
    rating_him: 0,
    rating_her: 0,
    rating_avg: 0,
    price_level: 3,
    would_return: null,
    story: null,
    comment_him: null,
    comment_her: null,
    lat: 41.9028,
    lng: 12.4964,
    photos: [
      'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: true,
    priority: 'alta',
    budget: '$$$',
    planned_year: 2026,
    tags: ['europa', 'historia', 'arte'],
  },
  {
    id: '11',
    created_at: '2026-01-01T00:00:00Z',
    name: 'San Andrés',
    type: 'ciudad',
    city: 'San Andrés',
    country: 'Colombia',
    visit_date: '',
    rating_him: 0,
    rating_her: 0,
    rating_avg: 0,
    price_level: 2,
    would_return: null,
    story: null,
    comment_him: null,
    comment_her: null,
    lat: 12.5847,
    lng: -81.7006,
    photos: [
      'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: true,
    priority: 'media',
    budget: '$$',
    planned_year: 2026,
    tags: ['playa', 'caribe', 'isla'],
  },
  {
    id: '12',
    created_at: '2026-01-01T00:00:00Z',
    name: 'Santa Marta',
    type: 'ciudad',
    city: 'Santa Marta',
    country: 'Colombia',
    visit_date: '',
    rating_him: 0,
    rating_her: 0,
    rating_avg: 0,
    price_level: 2,
    would_return: null,
    story: null,
    comment_him: null,
    comment_her: null,
    lat: 11.2408,
    lng: -74.1990,
    photos: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    ],
    is_favorite: false,
    is_planned: true,
    priority: 'media',
    budget: '$$',
    planned_year: 2026,
    tags: ['playa', 'caribe', 'naturaleza'],
  },
]

export const timelineEvents = [
  { date: 'Febrero 2024', title: 'Primera cita', place: 'La Trattoria, Bogotá', description: 'El principio de todo. Una mesa sin reserva y pasta perfecta.', photo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80', icon: '✦' },
  { date: 'Mayo 2024', title: 'Primer restaurante asiático', place: 'Sushi Nikkei, Bogotá', description: 'Descubrimos que los dos amamos el sushi.', photo: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80', icon: '◆' },
  { date: 'Julio 2024', title: 'Primer viaje juntos', place: 'El Cocuy, Boyacá', description: 'La montaña nos enseñó que podíamos con cualquier cosa.', photo: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', icon: '▲' },
  { date: 'Noviembre 2024', title: 'Primer pueblo pequeño', place: 'Mompox, Bolívar', description: 'Un pueblo detenido en el tiempo. El río, los pelícanos.', photo: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&q=80', icon: '◉' },
  { date: 'Marzo 2025', title: 'Primera noche de hotel', place: 'Hotel W, Bogotá', description: 'Una noche especial en la ciudad que nos vio conocernos.', photo: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80', icon: '◈' },
  { date: 'Abril 2025', title: 'Primer viaje a la costa', place: 'Cartagena, Bolívar', description: 'Las murallas al atardecer. El mejor viaje que hemos hecho.', photo: 'https://images.unsplash.com/photo-1583682064285-79b3d7bcf5b5?w=800&q=80', icon: '★' },
  { date: 'Junio 2025', title: 'Pueblo de boyacá', place: 'Mongüí, Boyacá', description: 'Frío, neblina y chocolate caliente en la plaza.', photo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', icon: '◆' },
  { date: 'Agosto 2025', title: 'Villa de Leyva', place: 'Villa de Leyva, Boyacá', description: 'Las calles empedradas y la comida perfecta.', photo: 'https://images.unsplash.com/photo-1598887142487-3c854d51eabb?w=800&q=80', icon: '✦' },
]
